baseURL = "https://fuxonauts.de/"

defaultContentLanguage = "de"

theme = [ "LoveIt", "hugo-shortcode-gallery" ]

[params]
  # LoveIt theme version
  version = "0.2.X"
  galleryLoadJQuery = true
  [params.header]
    [params.header.title]
      logo = "/lib/img/Logo.png"
  [params.footer]
    enable = false
  [params.home.profile]
    enable = false
  [params.home.posts]
    enable = true

[languages]
  [languages.de]
    weight = 1
    title = "Fuxonauts"
    languageCode = "de"
    languageName = "Deutsch"
    [[languages.de.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Termine/Kontakt"
      url = ""
      # title will be shown when you hover on this menu link
      title = ""
      weight = 1
    [[languages.de.menu.main]]
      identifier = "demands"
      pre = ""
      post = ""
      name = "Über uns"
      url = "about/"
      title = ""
      weight = 3
    [[languages.de.menu.main]]
      identifier = "bees"
      pre = ""
      post = ""
      name = "Bienen & Klima"
      url = "bees/"
      title = ""
      weight = 4
    [[languages.de.menu.main]]
      identifier = "links"
      pre = ""
      post = ""
      name = "Links"
      url = "links/"
      title = ""
      weight = 5
    [[languages.de.menu.main]]
      identifier = "gallery"
      pre = ""
      post = ""
      name = "Fotogalerien"
      url = "galleries/"
      title = ""
      weight = 6
    [[languages.de.menu.main]]
      identifier = "imprint"
      pre = ""
      post = ""
      name = "Impressum"
      url = "imprint/"
      title = "Impressum"
      weight = 7

  [languages.en]
    weight = 2
    title = "Fuxonauts"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "Events/Contact"
      url = ""
      # title will be shown when you hover on this menu link
      title = ""
      weight = 1
    [[languages.en.menu.main]]
      identifier = "demands"
      pre = ""
      post = ""
      name = "About us"
      url = "about/"
      title = ""
      weight = 3
    [[languages.en.menu.main]]
      identifier = "bees"
      pre = ""
      post = ""
      name = "Bees & Climate"
      url = "bees/"
      title = ""
      weight = 4
    [[languages.en.menu.main]]
      identifier = "links"
      pre = ""
      post = ""
      name = "Links"
      url = "links/"
      title = ""
      weight = 5
    [[languages.en.menu.main]]
      identifier = "gallery"
      pre = ""
      post = ""
      name = "Photo Galleries"
      url = "galleries/"
      title = ""
      weight = 6
    [[languages.en.menu.main]]
      identifier = "imprint"
      pre = ""
      post = ""
      name = "Imprint"
      url = "imprint/"
      title = ""
      weight = 7

[taxonomies]
  genre = "genres"
  organizer = "organizers"
  walk = "walks"
  kid = "kids"


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # LoveIt NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # LoveIt NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
