backend:
  name: github
  repo: fuxonauts/webpage-content
  branch: master
  base_url: https://oauth.fuxonauts.de
media_folder: static/img
public_folder: /img
i18n:
  structure: multiple_files
  locales: [de,en]
  default_locale: de
collections:
  - name: 'pre_post'
    label: 'Kontakt'
    folder: 'content/pre_posts/'
    path: 'pre'
    create: false
    i18n: true
    editor:
      preview: false
    fields:
      - { label: 'Kontakt', name: 'body', widget: 'markdown', i18n: true }
  - name: 'post'
    label: 'Termine'
    folder: 'content/posts/'
    path: '{{slug}}/index'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    i18n: true
    editor:
      preview: false
    fields:
      - { label: 'Datum und Uhrzeit', name: 'end', widget: 'datetime', date_format: 'DD.MM.YYYY', time_format: 'HH:mm' }
      - { label: 'Titel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown', i18n: true }
  - name: "demands"
    label: "Über uns"
    folder: 'content/about/'
    create: false
    i18n: true
    slug: 'about'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', i18n: true }
  - name: "bees"
    label: "Bienen & Klima"
    folder: 'content/bees/'
    create: false
    i18n: true
    slug: 'bees'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', i18n: true }
  - name: "links"
    label: "Links"
    folder: 'content/links/'
    create: false
    i18n: true
    slug: 'links'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', i18n: true }
  - name: 'gallery'
    label: 'Fotogallerie'
    folder: 'content/galleries/'
    create: true
    i18n: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Bilder', name: 'images', widget: 'image', allow_multiple: true, media_folder: 'images' }
      - { label: 'Gallery Code', name: 'body', widget: 'hidden', default: "{{< gallery match=\"images/*\" sortOrder=\"desc\" rowHeight=\"300\" margins=\"20\" resizeOptions=\"600x600 q90 Lanczos\" showExif=true previewType=\"blur\" embedPreview=\"true\" thumbnailHoverEffect=\"enlarge\" >}}" }
  - name: "imprint"
    label: "Impressum"
    folder: 'content/'
    create: false
    i18n: true
    slug: 'imprint'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', i18n: true }
      - { label: 'Inhalt', name: 'body', widget: 'markdown', i18n: true }

